name: Build and publish a Docker image on GHCR

on: [ push ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create list of Docker tags
        id: docker_tags
        shell: bash
        run: |
          GIT_BRANCH=${GITHUB_REF#refs/heads/}
          GIT_SHA_SHORT=$(git rev-parse --short HEAD)
          TAGS=${GIT_BRANCH},${GIT_BRANCH}.${GIT_SHA_SHORT}
          if [ ${GIT_BRANCH} = master ]
            TAGS=${TAGS},latest
          fi

          echo "::set-output name=docker_tags::${TAGS}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/reddit-no-google-amp-bot:${{ steps.docker_tags.outputs.docker_tags }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
